<form id="opc-discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post">
    <div class="discount">
        <div class="discount-form">
<!-- customization 		
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code:') ?></label>            
-->			
            <div class="input-box">
                <input placeholder="Enter your coupon code" class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" autocomplete="off"/>
            </div>
            <div class="buttons-set">
<!-- customization							
                <button type="button" title="<?php echo $this->__('Apply') ?>" class="button apply-coupon"  value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
-->
<!-- customization begin -->
                <button type="button" title="<?php echo $this->__('Apply') ?>" class="button apply-coupon"  value="<?php echo $this->__('Apply') ?>">
					<span><span><?php echo $this->__('Apply') ?></span></span>
				</button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button remove-coupon left"  value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
				<?php endif;?>
<!-- customization end -->
<!-- customization							
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button remove-coupon right"  value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
                <?php endif;?>
-->				
            </div>
        </div>
    </div>
</form>