<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                    <?php $isLogin = $this->helper('customer')->isLoggedIn()?>
                    <?php if(!$isLogin){?>
                        <?php $user = $this->helper('fblogin')->getFbUser()?>
                        <?php if(!$user || !$user['email']){?>
                        <a class="fb_button fb_button_medium f-right" onclick="login();return false;" href="#">
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/images/magestore/fblogin/f_login.png" >
                        </a>
                    <?php }else{?>
                        <a class="fb_button fb_button_medium f-right" onclick="window.location.href = '<?php echo $this->getFbloginUrl() ?>';">
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/images/magestore/fblogin/f_login.png">
                        </a>
                    <?php }?>
                        <script src="https://connect.facebook.net/en_US/all.js"></script>
                        <script type="text/javascript">
                            <?php if (!$user) { ?>
                            var newwindow;
                            var intId;
                            function login(){
                                var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
                                var	 screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
                                var	 outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
                                var	 outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
                                var	 width    = 500;
                                var	 height   = 270;
                                var	 left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
                                var	 top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
                                var	 features = (
                                    'width=' + width +
                                        ',height=' + height +
                                        ',left=' + left +
                                        ',top=' + top
                                    );

                                newwindow=window.open('<?php echo $this->getFbLoginButtonUrl() ?>','Login_by_facebook',features);

                                if (window.focus) {
                                    newwindow.focus()
                                }
                                return false;
                            }
                            <?php } ?>
                        </script>
                    <?php }?>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content">
                    <h2><?php echo $this->__('Registered Customers') ?></h2>
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
<?php /* Begin rememberme customisation */ ?>
                        <li>
                            <div class="input-box">
                                <label for="rememberme" class="input-box remember"><input type="checkbox" name="login[rememberme]" class="checkbox left" id="rememberme" title="<?php echo $this->__('Remember me') ?>" style="margin-top: 2px" />
                                <?php echo $this->__('Remember password') ?></label>
                            </div>
                        </li>
<?php /* End rememberme customisation */ ?>
                    </ul>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
