<?php $quote = Mage::getSingleton('checkout/session')->getQuote();
	  $store_id = Mage::app()->getStore()->getId();
	  $buy_credit = $quote->getMwStorecreditBuyCredit();

   if($buy_credit > 0):?>
	<tr>
	    <td colspan="3" class="a-right" colspan="1"><?php echo Mage::helper("storecreditpro")->__("Earn Credit");?></td>
	    <td class="a-right"><span class="price"><?php echo $buy_credit ?></span></td>
	</tr>
<?php endif;?>