<?php
?>
<?php $_helper = Mage::helper('onepagecheckout'); ?>
<div class="hor-line"></div>
<div class="col2-set">
    <div class="col-1">
        <h3><?php echo $this->__('Checkout without logging in') ?></h3>
           <?php if($_helper->isGuestEnabled()): ?>
                <?php echo $this->__('You don’t need to create an account to place an order. But you will have the option to register during checkout.');?>
                <input type="hidden" name="checkout_method" id="login:guest" value="guest" checked="checked" />
           <?php else : ?>
                <?php echo $this->__('You need to create an account to place an order. You will be prompted to register during checkout.');?>
                <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
           <?php endif; ?>
    </div>
    <div class="col-2">
        <h3><?php echo $this->__('Log in and checkout') ?></h3>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
</div>
<div class="col2-set">
    <div class="col-1">
        <div class="buttons-set">
            <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue Checkout') ?></span></span></button>
        </div>
    </div>
    <div class="col-2">
        <div class="buttons-set">
            <a style="margin-top:-25px;" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
            <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login and Checkout') ?></span></span></button>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
