<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>" class="no-border-right">&nbsp;</th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Code') ?></span></th>
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Wishlist') ?></span></th>
                        <?php endif ?>
                        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Quantity') ?></th>
                        <th colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="cart-extra">
<!-- customization
            <ul class="cart-extra-tab">
            <?php if (!$this->getIsVirtual()):?>
                <li class="tax-tab expanded"><?php echo $this->__('Estimate shipping & taxes') ?></li>
            <?php endif; ?>    
                <li class="coupon-tab"><?php echo $this->__('Discount code') ?></li>
            </ul>
-->
            <div class="akordeon">
                <div class="item-coupon akordeon-item">
                    <div class="akordeon-item-head">
                        <div class="akordeon-item-head-container">
                            <div class="akordeon-heading">
                                <?php echo $this->__('Discount code') ?>
                            </div>
                        </div>
                    </div>
                    <div class="akordeon-item-body">
                        <div class="akordeon-item-content">
                            <?php echo $this->getChildHtml('coupon') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
/* customization				
                jQuery('.cart-extra .akordeon').akordeon({ buttons: false, toggle: false });
*/				
                jQuery('.cart-extra-tab li').click(function(){
                    if(jQuery(this).hasClass('tax-tab')){
                        jQuery('.item-tax .akordeon-item-head-container').click();
                    }
                    if(jQuery(this).hasClass('coupon-tab')){
                        jQuery('.item-coupon .akordeon-item-head-container').click();
                    }
                    jQuery(this).parent().children('.expanded').removeClass('expanded');
                    jQuery(this).addClass('expanded');
                });
            });
        </script>
        <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php
                $i = 0;
            ?>
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li class="<?php echo ($i==0)?'first':''; ?>"><?php echo $methodHtml; ?></li>
                <?php
                    $i++;
                ?>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".qty_inc").each(function(){
            jQuery(this).on('click', function(e){
                jQuery(this).parent().parent().children("input.qty").val((+jQuery(this).parent().parent().children("input.qty").val() + 1) || 0);
                e.preventDefault();
            });
        });
        jQuery(".qty_dec").each(function(){
            jQuery(this).on('click',function(e){
                var qty_val = jQuery(this).parent().parent().children("input.qty").val();
                if(qty_val - 1 > 0)
                    qty_val = qty_val - 1;
                else
                    qty_val = 0;
                jQuery(this).parent().parent().children("input.qty").val(qty_val);
                e.preventDefault();
            });
        });
    });
</script>
