<?php $_option = $this->getOption(); ?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo  $this->htmlEscape($_option->getTitle()) ?></label>

<!-- customization begin - added question mark and lightbox functionality next to the "Your Word" input field -->
<?php  
    if ($_option->getTitle() == "Your Word") 
    {
?>

<?php
    // Light box settings
    
    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
// echo var_dump($_lightboxConfig);
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {    
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {              
        $mainImageSize = array(265, 265);
    }
    /* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    } 
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }
?>

<a href="#" 
    rel="lightbox" 
    title=""
    onclick="return false;"
><img src="<?php echo $this->getSkinUrl('images/question_mark.png'); ?>" class="question_mark"/></a>

<?php
    } 
?>

    
<!-- customization end -->

    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_FIELD): ?>
<!-- customization begin - only allow uppercase chars, numbers, and & -->	
        <input type="text" onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="input-text<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php if ($_option->getTitle() == 'Your Word'){ echo 'validate-myintent-chars'; } ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->escapeHtml($this->getDefaultValue()) ?>" />
<!-- customization end -->		
<!-- customization 	
        <input type="text" onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="input-text<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->escapeHtml($this->getDefaultValue()) ?>" />
-->		
    <?php elseif ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_AREA): ?>
        <textarea id="options_<?php echo $_option->getId() ?>_text" onchange="opConfig.reloadPrice()" class="<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]" rows="5" cols="25"><?php echo $this->escapeHtml($this->getDefaultValue()) ?></textarea>
    <?php endif; ?>
    <?php if ($_option->getMaxCharacters()): ?>
        <p class="note"><?php echo Mage::helper('catalog')->__('Maximum number of characters:')?> <strong><?php echo $_option->getMaxCharacters() ?></strong></p>
    <?php endif; ?>
    </div>
</dd>


<script type="text/javascript">

function initLightbox(){
    new Lightbox({
//        fileLoadingImage: "http://localhost/skin/frontend/default/default/images/lightbox/loading.gif",
//        fileBottomNavCloseImage: 'http://localhost/skin/frontend/default/default/images/lightbox/closelabel.gif',
        fileLoadingImage: "<?php echo $this->getSkinUrl('images/lightbox/loading.gif'); ?>",
        fileBottomNavCloseImage: "<?php echo $this->getSkinUrl('images/lightbox/closelabel.gif'); ?>"//,
//        overlayOpacity: <?php echo $_lightboxConfig['overlayOpacity'] ?>,
        animate: <?php echo (($_lightboxConfig['animate'] > 0)? "1":"0"); ?>,
        resizeSpeed: <?php echo $_lightboxConfig['resizeSpeed'] ?>,
        borderSize: <?php echo $_lightboxConfig['borderSize'] ?>,
        labelImage: '<?php echo $_lightboxConfig['labelImage'] ?>',
        labelOf: '<?php echo $_lightboxConfig['labelOf'] ?>'
    });
}


if (Prototype.Browser.IE) {
    Event.observe(window, 'load', function(){ //KB927917 fix
        initLightbox();
    });
} else {
    document.observe("dom:loaded", function(){
        initLightbox();
    });
}

</script>
