
<?php $isLogin = $this->helper('customer')->isLoggedIn()?>
<?php if(!$isLogin){?>
    <?php $user = $this->helper('fblogin')->getFbUser()?>
    <?php if(!$user || !$user['email']){?>
        <a class="fb_button fb_button_medium f-right" onclick="login();return false;" href="#">
<!-- customization
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/images/magestore/fblogin/f_login.png" >
-->
<!-- customization begin -->
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/myintent/images/f_login.png" >
<!-- customization end -->
        </a>
    <?php }else{?>
        <a class="fb_button fb_button_medium f-right" onclick="window.location.href = '<?php echo $this->getFbloginUrl() ?>';">
<!-- customization		
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/default/images/magestore/fblogin/f_login.png">
-->
<!-- customization begin -->
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/myintent/images/f_login.png">
<!-- customization end -->
        </a>
    <?php }?>
    <script src="https://connect.facebook.net/en_US/all.js"></script>
    <script type="text/javascript">
        <?php if (!$user) { ?>
        var newwindow;
        var intId;
        function login(){
            var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
            var	 screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
            var	 outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
            var	 outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
            var	 width    = 500;
            var	 height   = 270;
            var	 left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
            var	 top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
            var	 features = (
                'width=' + width +
                    ',height=' + height +
                    ',left=' + left +
                    ',top=' + top
                );

            newwindow=window.open('<?php echo $this->getFbLoginButtonUrl() ?>','Login_by_facebook',features);

            if (window.focus) {
                newwindow.focus()
            }
            return false;
        }
        <?php } ?>
    </script>
<?php }?>

