<?php
/**
 * Grid template
 */
?>

<?php $_giftCard = $this->getGiftVoucher() ?>

<div class="page-title">
    <h1><?php echo $this->__('Email Gift Card to Friend') ?></h1>
</div>
<div class="gift-card">
<?php echo $this->getChildHtml('giftvoucher.basic') ?>

<form id="email-giftcard-tofriend" method="post" action="<?php echo $this->getUrl('*/*/sendEmail') ?>">
    <h2 class="sub-title"><?php echo $this->__('Email to a Friend') ?></h2>
    <div class="form-group">
        <input name="giftcard_id" type="hidden" value="<?php echo $_giftCard->getId() ?>" />
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <label class="required" for="recipient_name"><?php echo $this->__('Name') ?><em>*</em></label>
                <input type="text" class="input-text required-entry form-control" value="<?php echo $_giftCard->getRecipientName() ?>" id="recipient_name" name="recipient_name" />
            </div>
            <div class="col-sm-6 col-xs-12">
                <label class="required" for="recipient_email"><?php echo $this->__('Email Address') ?><em>*</em></label>
                <input type="text" class="input-text required-entry form-control validate-email" value="<?php echo $_giftCard->getRecipientEmail() ?>" id="recipient_email" name="recipient_email" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="required" for="message"><?php echo $this->__('Message') ?><em>*</em></label>
        <textarea name="message" class="input-text required-entry form-control" id="message" cols="3" rows="3"><?php echo $_giftCard->getMessage() ?></textarea>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-xs-6 text-left">
                <a href="#" onclick="setLocation('<?php echo $this->getUrl('*/*/index') ?>');return false;">
                    <small>« </small>
                    <?php echo $this->__('Back') ?>
                </a>
            </div>
            <div class="col-xs-6 text-right">
                <p class="required"><em> * </em>Required Fields</p>
                <button type="submit" class="button">
                    <span>
                        <span><?php echo $this->__('Send to Friend') ?></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</form>
</div>
<script type="text/javascript">
    var emailGiftcardTofriendForm = new VarienForm('email-giftcard-tofriend',true);
</script>
