<form id="co-billing-form" action="" style="display:none">
<fieldset>
<!-- customization - begin -->
	<?php echo $this->getChildHtml('payment'); ?>
<!-- customization - end -->

    <ul class="form-list">

<!-- customization - begin -->	
    <?php if ($this->canShip()): ?>
        <li class="control">
            <input type="checkbox" name="billing[same_as_shipping]" id="billing:same_as_shipping" value="0" title="Same as shipping address" class="checkbox" onclick="billing.setSameAsShipping(this.checked)"/><label for="billing:same_as_shipping">Same as shipping address</label></li>
        </li>
    <?php endif; ?>
<!-- customization - end -->
	
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
<!-- customization begin -->
<!--
			<div id="billing_fields_visible" style="visibility: hidden; position: absolute">
-->	
			<div id="billing_fields_visible" style="">
<!-- customization end -->			
            <ul>
                <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <li class="wide">
                    
                        <div class="input-box">
                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text resettable <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" placeholder="<?php echo $this->__('Company') ?>" />
                        </div>
                  
<!--					
        <?php if(!$this->isCustomerLoggedIn()): ?>
                    <div class="field">
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('Email Address') ?> *"/>
                        </div>
                    </div>
        <?php endif; ?>
-->		
                </li>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text resettable <?php echo $_streetValidationClass ?>" placeholder="<?php echo $this->__('Address') ?>1 *"/>
                    </div>
                </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text resettable <?php echo $_streetValidationClass ?>" placeholder="<?php echo $this->__('Address') ?>2"/>
                    </div>
                </li>
        <?php endfor; ?>
                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" placeholder="<?php echo $this->__('VAT Number') ?>" />
                    </div>
                </li>
                <?php endif; ?>
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text resettable <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" placeholder="<?php echo $this->__('City') ?> *" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('State/Province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text resettable <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" placeholder="<?php echo $this->__('State/Province') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text resettable validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?> *" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text resettable <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" placeholder="<?php echo $this->__('Telephone') ?> *" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text resettable <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="billing:fax" placeholder="<?php echo $this->__('Fax') ?>" />
                        </div>
                    </div>
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                <li class="fields">
                <?php if ($_dob->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif; ?>
                <?php if ($_gender->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif ?>
                </li>
            <?php endif ?>

            <?php if ($this->isTaxvatEnabled()):?>
                <li><?php echo $this->getTaxvatHtml() ?></li>
            <?php endif; ?>
<!--
                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" placeholder="<?php echo $this->__('Password') ?> *" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" placeholder="<?php echo $this->__('Confirm Password') ?> *" />
                        </div>
                    </div>
                </li>
-->				
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?php echo $this->getChildHtml('form.additional.info'); ?>					
            </ul>
<!--  customization begin -->			
			</div> <!-- div#billing_fields_visible -->
<!-- customization end -->			
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </fieldset>
    </li>
<!-- customization begin -->
	<?php if(!$this->isCustomerLoggedIn()): ?>
		<li class="wide">
			<div class="input-box">
				<input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('Email Address') ?> *"/>
			</div>
        </li>
		<li class="control">
            <input type="checkbox" name="billing[create_account]" value="1" title="Create account for later use" id="billing:create_account" onchange="checkout.setMethod(this);" class="checkbox" />
			<label for="billing:create_account">Create account for later use</label>
		</li>
					
		<li class="fields" id="register-customer-password" style="display:none;">
			<div class="field">
				<div class="input-box">
					<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" placeholder="<?php echo $this->__('Password') ?> *" />
				</div>
			</div>
			<div class="field">
				<div class="input-box">
					<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" placeholder="<?php echo $this->__('Confirm Password') ?> *" />
				</div>
			</div>
		</li>
	<?php endif; ?>					
<!-- customization end -->	
<!--
    <?php if ($this->canShip()): ?>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></li>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
        </li>
    <?php endif; ?>
-->
    </ul>
<!--	
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
-->

    <div class="buttons-set" id="billing-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>

</fieldset>
</form>

<!-- customization begin - insert billing and payment progress bar -->
<div id="payment-progress-opcheckout" style="visibility:hidden; position:absolute;">
	<?php echo $this->getChildHtml('payment.progress'); ?>
</div>
<div id="billing-progress-opcheckout" style="visibility:hidden; position:absolute;">
	<?php echo $this->getChildHtml('billing.progress'); ?>
</div>
<!-- customization end -->



<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

/* customization begin */	
    billingForm.extraChildParams = ' onchange="billing.setSameAsShipping(false);"';
/* customization end */		

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
/* what is the purpose of the code below? hiding the select box for state causes validation to fail */	
    jQuery(document).ready(function(){
        var region_id = document.getElementById('billing:region_id');
        var country_id = document.getElementById("billing:country_id");
// where is the dynamic id, sbHolder*, used?  Didn't see if anywhere		
        if (!billingRegionUpdater.regions[billingRegionUpdater.countryEl.value]) {
            jQuery('#sbHolder_'+jQuery(region_id).attr("sb")).hide();
        }else{
            jQuery('#sbHolder_'+jQuery(region_id).attr("sb")).show();
        }
        billingRegionUpdater.update();
// why hide select box for state?		
//        jQuery(region_id).hide();
        jQuery(country_id).change(function(){
            var region_id = document.getElementById('billing:region_id');
            var country_val = '';
            jQuery(this).children('option').each(function(){
                if(jQuery(this).attr('selected')){
                    country_val = jQuery(this).attr('value');
                }
            });
            billingRegionUpdater.countryEl.value = country_val;
// where is the dynamic id, sbHolder*, used?  Didn't see if anywhere			
            if (!billingRegionUpdater.regions[billingRegionUpdater.countryEl.value]) {
                jQuery('#sbHolder_'+jQuery(region_id).attr("sb")).hide();
            }else{
                jQuery('#sbHolder_'+jQuery(region_id).attr("sb")).show();
            }
            billingRegionUpdater.update();
// why hide select box for state?			
//            jQuery(region_id).hide();
        });
    });
//]]>
</script>